app_management/urls.py
from django.conf.urls import url

from . import views

app_name = 'app'
urlpatterns = [
    url(r'^create', views.AppCreateView.as_view(), name='app-create'),
    url(r'^update/(?P<pk>\d+)',
        views.AppUpdateView.as_view(),
        name='app-update'),
    url(r'^new_version/(?P<pk>\d+)', views.AppVersionCreateView.as_view(),
        name='app-new-version'),
    url(r'^$', views.AppListView.as_view(), name='app-list'),
    url(r'^(?P<pk>\d+)/$', views.AppDetailView.as_view(), name='app_detail'),
    url(r'^download/(?P<pk>[a-zA-Z0-9_-]+)/$',
        views.DownloadTarballView.as_view(),
        name='app-download')
]

backworth/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^app/', include('app_management.urls')),
    url(r'^documentation/', include('documentation.urls')),
    url(r'^', include('main.urls')),
]

main/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView

from . import views


urlpatterns = [
    url(r'^sdk$', views.SdkTermsView.as_view(), name='sdk_terms'),
    url(r'^sdk-download$', views.SdkDownloadView.as_view(),
        name='sdk_download'),
    url(r'^profile', views.ProfileView.as_view(),
        name='user_home'),
    url(r'^$',
        TemplateView.as_view(template_name='home.html'),
        name='home'),
]

app_management/models.py
import os
from datetime import date

from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.conf import settings
from django.utils.text import slugify
from .checked_filefield import ContentTypeRestrictedFileField


def gen_app_slug(instance):
    initial = slugify(instance.title)

    cnt = 1
    instance.slug = '%s-%d' % (initial, cnt)

    while App.objects.filter(slug=instance.slug).exists():
        cnt += 1
        instance.slug = '%s-%d' % (initial, cnt)


class App(models.Model):
    # We don't enforce uniqueness on app titles
    title = models.CharField(
        max_length=200,
        help_text=('The display name for your app. '
                   'It does not have to be unique, but it is better '
                   'if it is (mandatory)'))
    slug = models.SlugField(unique=True)
    author = models.ForeignKey('auth.User')
    created_date = models.DateTimeField(blank=True, null=True)
    webpage = models.URLField(
        blank=True,
        help_text='Link to the webpage for this application (optional)')
    privacy_policy = models.URLField(
        blank=True,
        help_text='Link to the privacy policy for this application (optional)')

    (OTHER,
     COMMUNICATION,
     ENTERTAINMENT,
     NAVIGATION,
     MULTIMEDIA) = range(5)

    CATEGORY_CHOICES = (
        (OTHER, 'Other'),
        (COMMUNICATION, 'Communication'),
        (ENTERTAINMENT, 'Entertainment'),
        (NAVIGATION, 'Navigation'),
        (MULTIMEDIA, 'Multimedia'),
    )

    category = models.IntegerField(
        choices=CATEGORY_CHOICES,
        default=OTHER,
        help_text=('Pick the category that defines your '
                   'application best (mandatory)'))

    description = models.TextField(
        max_length=10000, blank=True,
        help_text=('A description of your application, with a '
                   'maximum of 10 000 characters (optional)'))

    def get_absolute_url(self):
        return reverse('app:app_detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        # We do not use add_now, for the reason why see:
        # http://stackoverflow.com/questions/1737017/django-auto-now-and-auto-now-add/1737078#1737078
        if not self.id:  # pragma: no cover
            self.created_date = timezone.now()
            gen_app_slug(self)

        # pylint: disable=no-member
        return super(App, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


def tarball_path_from_filename(instance, filename):
    path = os.path.join(
        instance.app.author.username,
        instance.app.title, instance.app.slug, 'tarballs',
        date.today().strftime('%Y/%m/%d'), os.path.basename(filename))

    final_path = path
    ctr = 1
    while os.path.exists(os.path.join(settings.MEDIA_ROOT, final_path)):
        final_path = '%s-%d' % (path, ctr)
        ctr += 1

    return final_path


class AppVersion(models.Model):
    semantic_version = models.CharField(
        max_length=200,
        help_text='For example 0.1, 8.2.5')
    uploader = models.ForeignKey('auth.User')
    uploaded_date = models.DateTimeField(blank=True, null=True)
    app = models.ForeignKey(App, related_name='versions')
    tarball = ContentTypeRestrictedFileField(
        upload_to=tarball_path_from_filename,
        content_types=['application/x-gzip',
                       'application/x-tar',
                       'application/zip',
                       'application/x-zip',
                       'application/x-zip-compressed'])
    accepted = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('app:app_detail', kwargs={'pk': self.app.pk})

    def save(self, *args, **kwargs):
        if not self.id:  # pragma: no cover
            self.uploaded_date = timezone.now()
        # pylint: disable=no-member
        return super(AppVersion, self).save(*args, **kwargs)

    def get_tarball_link(self):
        if not self.pk:
            return None
        else:
            return '/app/download/%d/' % self.pk

    def tarball_link(self):
        if self.pk:
            return "<a href='%s'>Download tarball</a>" % \
                self.get_tarball_link()
        else:
            return "No tarball to download"

    tarball_link.allow_tags = True

    def __str__(self):
        return '%s %s' % (str(self.app), self.semantic_version)

app_management/forms.py
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from .models import App, AppVersion


class AppForm(ModelForm):

    class Meta:
        model = App
        fields = ['title', 'category', 'webpage', 'privacy_policy',
                  'description']


AppVersionFormSet = inlineformset_factory(
    App, AppVersion, fields=['semantic_version', 'tarball'],
    extra=1, can_delete=False)

app_management/views.py
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import DetailView, ListView
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect, Http404
from django_downloadview import ObjectDownloadView
from .models import App, AppVersion
from .forms import AppVersionFormSet, AppForm


class ValidatedUserRequiredMixin(UserPassesTestMixin):
    permission_denied_message = ("New users need to be validated "
                                 "by our staff before accessing this feature")

    def test_func(self):
        return self.request.user.groups.filter(name='validated_user').exists()\
            or self.request.user.is_superuser

    def handle_no_permission(self):
        if self.request.user.is_authenticated():
            raise PermissionDenied(self.permission_denied_message)
        return super(ValidatedUserRequiredMixin, self).handle_no_permission()


class AppCreateView(ValidatedUserRequiredMixin, CreateView):
    model = App
    form_class = AppForm

    def get(self, request, *args, **kwargs):
        # pylint: disable=attribute-defined-outside-init
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        app_version_form = AppVersionFormSet()
        return self.render_to_response(
            self.get_context_data(form=form,
                                  app_version_form=app_version_form))

    def post(self, request, *args, **kwargs):
        # pylint: disable=attribute-defined-outside-init
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        app_version_form = AppVersionFormSet(self.request.POST,
                                             self.request.FILES)
        if form.is_valid() and app_version_form.is_valid():
            return self.form_valid(form, app_version_form)
        else:
            return self.form_invalid(form, app_version_form)

    # pylint: disable=arguments-differ
    def form_valid(self, form, app_version_form):
        app = form.save(commit=False)
        # We're protected by the LoginRequired mixin, user has to be != None
        app.author = self.request.user
        app.save()
        app_version_form.instance = app
        app_versions = app_version_form.save(commit=False)

        for app_version in app_versions:
            app_version.app = app
            app_version.uploader = self.request.user
            app_version.save()

        return HttpResponseRedirect(app.get_absolute_url())

    # pylint: disable=arguments-differ
    def form_invalid(self, form, app_version_form):
        return self.render_to_response(
            self.get_context_data(form=form,
                                  app_version_form=app_version_form))


class AppUpdateView(LoginRequiredMixin, UpdateView):
    model = App
    fields = ['category', 'webpage', 'privacy_policy', 'description']
    template_name_suffix = '_update_form'


class AppDetailView(ValidatedUserRequiredMixin, DetailView):
    model = App

    def get_queryset(self):
        qs = super(AppDetailView, self).get_queryset()
        return qs.filter(author=self.request.user)


class AppListView(ValidatedUserRequiredMixin, ListView):
    model = App

    def get_queryset(self):
        return App.objects.filter(author=self.request.user)


class AppVersionCreateView(LoginRequiredMixin, CreateView):
    model = AppVersion
    fields = ['semantic_version', 'tarball']

    def dispatch(self, *args, **kwargs):
        pk = kwargs.get('pk')

        try:
            app = App.objects.get(pk=pk)
        except App.DoesNotExist:
            raise Http404("App %s does not exist" % pk)

        if self.request.user != app.author:
            raise Http404("App %s does not exist" % pk)

        # pylint: disable=no-member
        # pylint: disable=bad-super-call
        return super(CreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        obj = form.save(commit=False)

        pk = self.kwargs.get('pk')
        obj.app = App.objects.get(pk=pk)

        obj.uploader = self.request.user
        obj.save()
        return HttpResponseRedirect(obj.get_absolute_url())


class DownloadTarballView(LoginRequiredMixin, ObjectDownloadView):
    model = AppVersion
    file_field = 'tarball'

    def get(self, *args, **kwargs):
        pk = kwargs.get('pk')

        try:
            app_version = AppVersion.objects.get(pk=pk)
        except AppVersion.DoesNotExist:
            raise Http404("App version %s does not exist" % pk)

        if app_version.app.author != self.request.user and \
                not self.request.user.is_superuser:
            raise Http404("App version %s does not exist" % pk)

        return super(DownloadTarballView, self).get(*args, **kwargs)

templates/app_management/app_detail.html
{% extends "base.html" %}

{% block content %}
<h1>Details for application: {{ object.title }}</h1>

<a href="{% url 'app:app-update' app.pk %}" class="btn btn-primary">Update details</a>

<h2>
    Creation date:
</h2>

<p>
{{ object.created_date }}
</p>

<h2>
	Webpage:
</h2>

<p>
{% if object.webpage %}
{{ object.webpage }}
{% else %}
No webpage currently defined
{% endif %}
</p>

<h2>
	Privacy policy:
</h2>

<p>
{% if object.privacy_policy %}
{{ object.privacy_policy }}
{% else %}
No privacy policy currently defined
{% endif %}
</p>

<h2>
	Description:
</h2>

<p>
{% if object.description %}
{{ object.description }}
{% else %}
No description currently defined
{% endif %}
</p>

<h2>
	Category:
</h2>

<p>
{{ object.get_category_display }}
</p>

<h2>Versions</h2>

<p><a href="{% url 'app:app-new-version' app.pk %}" class="btn btn-primary">Propose a new version</a></p>

<ul class="list-group">
{% for version in object.versions.all %}
<li class="list-group-item">
	{{ version.semantic_version }}
	{% if version.accepted %}
	<span class="label label-primary label-pill pull-right">
	Accepted
	</span>
	{% else %}
	<span class="label label-default label-pill pull-right">
	Not accepted
	</span>
	{% endif %}
</li>
{% endfor %}
</ul>

{% endblock %}

templates/app_management/app_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}
| New application
{% endblock %}

{% block content %}
<h1>New application</h1>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
{% bootstrap_form form %}
<hr class="divider" />
<h2>Initial version</h2>
<p>
You can upload an initial version for this application.
This is not mandatory and can be done later as well.
</p>
{% bootstrap_formset app_version_form %}
{% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
</form>
{% endblock %}

templates/app_management/app_list.html
{% extends "base.html" %}

{% block content %}
<h1>My applications</h1>
<p><a href="{% url 'app:app-create' %}" class="btn btn-primary">Create new application</a></p>

<div class="table-responsive">
	<table class="table">
	<thead>
      	<tr>
        	<th>Title</th>
        	<th>Creation date</th>
		<th>Versions</th>
      	</tr>
    	</thead>
    	<tbody>
	{% for app in object_list %}
		<tr>
		<td><a href="{{ app.get_absolute_url }}">{{ app.title }}</a></td>
		<td>{{ app.created_date }}</td>
		<td>{{ app.versions.all|length }}</td>
		</tr>
	{% endfor %}
    	</tbody>
	</table>
</div>
{% endblock %}

templates/app_management/app_update_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}
| Update application
{% endblock %}

{% block content %}
<h1>Update application</h1>
<form action="" method="post">{% csrf_token %}
{% bootstrap_form form %}
{% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
</form>
{% endblock %}

templates/app_management/appversion_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<h1>New application version</h1>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
{% bootstrap_form form %}
{% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
</form>
{% endblock %}