app_management/urls.py
from django.conf.urls import url

from . import views

app_name = 'app'
urlpatterns = [
    url(r'^create', views.AppCreateView.as_view(), name='app-create'),
    url(r'^update/(?P<pk>\d+)',
        views.AppUpdateView.as_view(),
        name='app-update'),
    url(r'^new_version/(?P<pk>\d+)', views.AppVersionCreateView.as_view(),
        name='app-new-version'),
    url(r'^$', views.AppListView.as_view(), name='app-list'),
    url(r'^(?P<pk>\d+)/$', views.AppDetailView.as_view(), name='app_detail'),
    url(r'^download/(?P<pk>[a-zA-Z0-9_-]+)/$',
        views.DownloadTarballView.as_view(),
        name='app-download')
]

backworth/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^app/', include('app_management.urls')),
    url(r'^documentation/', include('documentation.urls')),
    url(r'^', include('main.urls')),
]

documentation/urls.py
from django.conf.urls import url

from . import views

app_name = 'documentation'

urlpatterns = [
    url(r'^media/(?P<filename>.+)', views.DocumentationRedirectView.as_view()),
    url(r'^assets/js/search/hotdoc_fragments/(?P<filename>.+)',
        views.DocumentationRawView.as_view()),
    url(r'^assets/(?P<filename>.+)',
        views.DocumentationRedirectView.as_view()),
    url(r'^dumped.trie', views.DocumentationRedirectView.as_view()),
    url(r'^(?P<pagename>.+)', views.DocumentationView.as_view(),
        name='documentation_page'),
]

main/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView

from . import views


urlpatterns = [
    url(r'^sdk$', views.SdkTermsView.as_view(), name='sdk_terms'),
    url(r'^sdk-download$', views.SdkDownloadView.as_view(),
        name='sdk_download'),
    url(r'^profile', views.ProfileView.as_view(),
        name='user_home'),
    url(r'^$',
        TemplateView.as_view(template_name='home.html'),
        name='home'),
]

templates/base.html
{% extends 'bootstrap3/bootstrap3.html' %}
{%load staticfiles %}

{% block bootstrap3_extra_head %}
{% block stylesheets %}{% endblock %}
<link rel="stylesheet" href="{% static "main/style.css" %}" type="text/css">
{% block scripts %}{% endblock %}

<link rel="apple-touch-icon" sizes="57x57" href="{% static "main/favicons/apple-touch-icon-57x57.png" %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static "main/favicons/apple-touch-icon-60x60.png" %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static "main/favicons/apple-touch-icon-72x72.png" %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static "main/favicons/apple-touch-icon-76x76.png" %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static "main/favicons/apple-touch-icon-114x114.png" %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static "main/favicons/apple-touch-icon-120x120.png" %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static "main/favicons/apple-touch-icon-144x144.png" %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static "main/favicons/apple-touch-icon-152x152.png" %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static "main/favicons/apple-touch-icon-180x180.png" %}">
<link rel="icon" type="image/png" href="{% static "main/favicons/favicon-32x32.png" %}" sizes="32x32">
<link rel="icon" type="image/png" href="{% static "main/favicons/favicon-194x194.png" %}" sizes="194x194">
<link rel="icon" type="image/png" href="{% static "main/favicons/favicon-96x96.png" %}" sizes="96x96">
<link rel="icon" type="image/png" href="{% static "main/favicons/android-chrome-192x192.png" %}" sizes="192x192">
<link rel="icon" type="image/png" href="{% static "main/favicons/favicon-16x16.png" %}" sizes="16x16">
<link rel="manifest" href="{% static "main/favicons/manifest.json" %}">
<link rel="mask-icon" href="{% static "main/favicons/safari-pinned-tab.svg" %}" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="{% static "main/favicons/mstile-144x144.png" %}">
<meta name="theme-color" content="#ffffff">

{% endblock %}

{% block bootstrap3_title %}
Apertis developer portal
{% block title %}
{% endblock %}
{% endblock %}

{% block bootstrap3_content %}
{% include "nav.html" %}

{% block header %}{% endblock %}

<div class="container-fluid">
	<div class="row">
		<div class="col-md-2 hidden-xs hidden-sm" id="sidenav-column">
			{% block sidenav %}{% endblock %}
		</div>
		<div class="col-md-8">
			{% block content %}{% endblock %}
		</div>
		<div class="col-md-2">
		</div>
	</div>
</div>

{% include "footer.html" %}

{% endblock %}

{% block bootstrap3_extra_script %}
<script src="{% static "main/navbar_offset_scroller.js" %}"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
         })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76952868-1', 'auto');
    ga('send', 'pageview');
</script>
{% block tail_scripts %}{% endblock %}
{% endblock %}

templates/footer.html
<footer class="appdev-footer">
	<div class="container">
		<hr class="divider">
		<ul class="appdev-footer-links">
			<li>
			<a href="mailto:sdk-support@apertis.org">Contact us</a>
			</li>
			<li>
			<a href="https://wiki.apertis.org/Apertis:Privacy_policy">Privacy policy</a>
			</li>
			<a href="https://wiki.apertis.org/Apertis:About">About Apertis</a>
		</ul>
		<p>
		Built by <a href="https://www.collabora.com/">Collabora</a>
		</p>
	</div>
</footer>

templates/home.html
{% extends "base.html" %}

{%load staticfiles %}

{% block content %}
<div class="appdev-masthead">
	<img id="appdev-logo" alt="Apertis logo" src="{% static "main/apertis_logo_blue.svg" %}"/>
	<p>Free and Open Source GNU/Linux-based In-Vehicle Infotainment platform</p>
	<div class="btn-group btn-group-vertical appdev-shortcuts" role="group">
		<a href="{% url 'documentation:documentation_page' 'index.html'%}" class="btn btn-outline-inverse btn-lg">Getting Started with App Development</a>


	</div>
</div>
<hr class="divider">
<div class="appdev-baseline">
	<h3>Quick Links:</h3>
	<h4><a href="{% url 'sdk_terms' %}">Download SDK</a>, <a href="{% url 'app:app-list' %}">Distribute</a>
		<a href="https://phabricator.apertis.org/">Phabricator</a> <a href="https://wiki.apertis.org/Main_Page">Wiki</a>
	</h4>
</div>
{% endblock %}

templates/nav.html
{%load staticfiles %}

<header class = "navbar navbar-inverse navbar-fixed-top appdev-navbar" role = "banner" id="nav-header">
	<div class = "container-fluid">
		<div class="row">
			<div class="col-md-2 hidden-xs hidden-sm" id="sidenav-column">
			</div>
			<div class="col-md-8">
				<div class ="navbar-header">
					<button type = "button" class= "navbar-toggle" data-toggle = "collapse" data-target = "#dropdown">
						<span class = "sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>

					<a href="{% url 'home' %}" class ="navbar-brand">
						<img alt="Apertis developer portal" src="{% static "main/apertis_logo.png" %}"/>
					</a>
				</div>

				<div class = "collapse navbar-collapse" id = "dropdown">
					<ul class = "nav navbar-nav navbar-right" role = "navigation">
						{% if user.is_authenticated %}
						<li {% if request.path|slice:":4" == '/sdk' %}class="active"{% endif %}>
							<a href="{% url 'sdk_terms' %}">Download</a>
						</li>
						{% endif %}
						<li {% if request.path|slice:":15" == '/documentation/' %}class="active"{% endif %}>
							<a href="{% url 'documentation:documentation_page' 'index.html'%}">Documentation</a>
						</li>
						{% if user.is_authenticated %}
						<li {% if request.path|slice:":5" == '/app/' %}class="active"{% endif %}>
							<a href="{% url 'app:app-list' %}">My applications</a>
						</li>
						<li><a href="{% url 'user_home' %}">Settings</a></li>
						<li><a href="/accounts/logout/">Logout</a></li>
						{% else %}
						<li><a href="/accounts/login/">Login</a></li>
						{% endif %}
					</ul>
				</div>
			</div>
			<div class="col-md-2">
			</div>
		</div>
	</div>
</header>

templates/profile.html
{% extends "base.html" %}
{% load bootstrap3 %}

{%load staticfiles %}

{% block content %}
{% if messages %}
<div class="alert alert-success">
	{% for message in messages %}
	{% if message.tags == "success" %}
	{{ message }}
	{% endif %}
	{% endfor %}
</div>
{% endif %}

<h1>My profile</h2>
<p>
<p><b>Email account</b></p>
{% if user.email %}
{{ user.email }}
{% else %}
No email set
{% endif %}
</p>
<p>
<a href="/accounts/email/" class="btn btn-primary">Manage accounts</a>
</p>
<p><b>Password</b></p>
<p>
<a href="/accounts/password/change/" class="btn btn-primary">Update password</a>
</p>


<form action="" method="post">
	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons submit='OK' %}{% endbuttons %}
</form><br />

{% endblock %}

templates/sdk_download.html
{% extends "base.html" %}

{% block content %}

<h1>
	Thanks for downloading our SDK!
</h1>

<p>
<a href="{{ download_link }}">
	Click this direct link if your download did not start automatically
</a>
</p>

<p>
While you're downloading, you may want to have a look at <a href="{% url 'documentation:documentation_page' 'index.html'%}">our documentation</a>, it contains an installation guide to get you started.
</p>

{% endblock %}

{% block tail_scripts %}
<script>
$(document).ready(function() {
		setTimeout(function() {
				window.location = "{{ download_link }}";
		}, 2000);
});
</script>
{% endblock %}

templates/sdk_terms.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block title %}
| SDK Download
{% endblock %}

{% block content %}
<h1>Download the SDK</h1>

<h2>Terms and Conditions</h2>

<p>
Copyright (c) 2015-2016 Collabora Limited
</p>
</p>
Copyright (c) 2015-2016 Robert Bosch Car Multimedia GmbH
</p>

<p>
<h3>Accepting this License Agreement</h3>
<ul>
	<li>In order to use the SDK, you must first agree to this License Agreement. You may not use the SDK if you do not accept this License Agreement.</li>
	<li>By clicking to accept, you hereby agree to the terms of this License Agreement.</li>
	<li>You may not use the SDK and may not accept the License Agreement if you are a person barred from receiving the SDK under the laws of the United States or other countries including the country in which you are resident or from which you use the SDK.</li>
	<li>If you are agreeing to be bound by this License Agreement on behalf of your employer or other entity, you represent and warrant that you have full legal authority to bind your employer or such entity to this License Agreement.</li>
	<li>If you do not have the requisite authority, you may not accept the License Agreement or use the SDK on behalf of your employer or other entity.</li>
</ul>
</p>

<p>
<h3>SDK License from Apertis</h3>
<ul>

<li>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:</li>

</li>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.</li>

<li>THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.</li>

</ul>
</p>

<form action="" method="post">{% csrf_token %}
{% bootstrap_form form %}
{% buttons submit='OK' %}{% endbuttons %}
</form>
{% endblock %}